
spring:
  profiles:
    active: dev

server:
  port: 8000
  address: localhost

storage:
  root: /data/storage_root

---
#development environmen
spring:
  profiles: dev
server:
  port: 8000
  address: localhost

storage:
  root: /data/storage_root0