server:
  port: 8888
  address: localhost

spring:
  redis:
    host: 192.168.15.101
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 8
    timeout: 10s

storage:
  root:/data/storage_root1
